### ISSUE TITLE
Create the list of all resources and pages where we have scrapable data and validate against the list provided 

### ISSUE THREAD

**Issue by Daniellappv** [CivicActions/ckanext-edscrapers#10]
**Description:** Replicate the job that the other team did so we are clear on the Dept Ed Websphere to scrape. Validate that against the other list and have an agreed scope of pages to scrape

## Acceptance criteria

- [x] We have the list of scrapable sites
- [x] We have validated it against the list provided by the other team 
- [x] We are aligned as a team on the Dept Ed Websphere to scrape

**Jira card**: https://open-data-ed.atlassian.net/browse/OD-499

---

**UPDATES Mar 5:**

Design and implement a reproducible way of validating the scrape results against the list provided. We need to be able to do this any time we want, as the scrapers run / collect more data.

Bonus points for a google sheets chart from the output, or anything similar.

Tasks:

- [x] Automate the validation process
- [x] Push automation code
- [x] Review & merge the code
- [ ] Document the extracted analytics from the data

**Comment by nightsh** [comment]
Final results documentation is still a WIP.

**Comment by nightsh** [comment]
Estimation for the docs: 2h
