### ISSUE TITLE
Output bucket for scraped files in github defined

### ISSUE THREAD

**Issue by Daniellappv** [CivicActions/ckanext-edscrapers#12]
**Description:** Define an output bucket in GitHub for all the scraped files. Super small, not worth an issue but let's go with the principle of tracking the work. 

## Acceptance criteria

- [x] Output bucket for scraped files in GitHub defined

**Link to Jira card:** https://open-data-ed.atlassian.net/browse/OD-505

**Comment by nightsh** [comment]
We have a branch called `output` that hosts the datajson files: https://github.com/CivicActions/ckanext-edscrapers/tree/output/output. Closing.
