### ISSUE TITLE
P2 Parsing: Office of Career, Technical and Adult Education

### ISSUE THREAD

**Issue by nightsh** [CivicActions/ckanext-edscrapers#19]
> ref. #4 

Create a HTML parser that integrates into the OCTAE scraper and replaces the existing dummy parser script.

https://www2.ed.gov/about/offices/list/ovae/index.html

Tasks:

- [x] identify the possible page structures in the target site
- [x] write one or multiple parsers that cover as many cases as possible
- [x] test if it runs well within the pipeline

Acceptance criteria:

- [x] we have a parser specific to this site that replaces the initial dummy parser
- [x] parser creates `Dataset` instances, each having at least one `Resource`
- [x] uses scrapy pipelines to dump datasets

TBD: List of potentially different structures and one or two false positives to test the scraper against.

**Comment by osahon-okungbowa** [comment]
All done with these tasks. Please review and close as necessary
