### ISSUE TITLE
P3 Parsing: Office of Postsecondary Education

### ISSUE THREAD

**Issue by nightsh** [CivicActions/ckanext-edscrapers#20]
> ref. #5 

Create a HTML parser that integrates into the OPE scraper and replaces the existing dummy parser script.

Tasks:

- [x] identify the possible page structures in the target site
- [x] write one or multiple parsers that cover as many cases as possible
- [x] test if it runs well within the pipeline

Acceptance criteria:

- [x] we have a parser specific to this site that replaces the initial dummy parser
- [x] parser creates `Dataset` instances, each having at least one `Resource`
- [x] uses scrapy pipelines to dump dataset

TBD: List of potentially different structures and one or two false positives to test the scraper against.

**Comment by osahon-okungbowa** [comment]
Will start work on this early tomorrow

**Comment by osahon-okungbowa** [comment]
All tasks completed. Pending pull request
