### ISSUE TITLE
P4 Parsing: Office of English Language Acquisition

### ISSUE THREAD

**Issue by nightsh** [CivicActions/ckanext-edscrapers#21]
> ref. #6 

Create a HTML parser that integrates into the OELA scraper and replaces the existing dummy parser script.

Tasks:

- [x] identify the possible page structures in the target site
- [x] write one or multiple parsers that cover as many cases as possible
- [x] test if it runs well within the pipeline

Acceptance criteria:

- [x] we have a parser specific to this site that replaces the initial dummy parser
- [x] parser creates `Dataset` instances, each having at least one `Resource`
- [x] parser dumps datasets with scrapy pipelines

TBD: List of potentially different structures and one or two false positives to test the scraper against.

**Comment by osahon-okungbowa** [comment]
Will commence work on this tomorrow

**Comment by osahon-okungbowa** [comment]
All done on these tasks
