### ISSUE TITLE
P6 Parsing: Office of Planning, Evaluation and Policy Development

### ISSUE THREAD

**Issue by nightsh** [CivicActions/ckanext-edscrapers#23]
> ref. #8

Create a HTML parser that integrates into the OPEPD scraper and replaces the existing dummy parser script.

Tasks:

- [x] identify the possible page structures in the target site
- [x] write one or multiple parsers that cover as many cases as possible
- [x] test if it runs well within the pipeline

Acceptance criteria:

- [x] we have a parser specific to this site that replaces the initial dummy parser
- [x] parser creates `Dataset` instances, each having at least one `Resource`
- [x] parser uses scrapy pipelines to dump datasets with resources

TBD: List of potentially different structures and one or two false positives to test the scraper against.

**Comment by osahon-okungbowa** [comment]
All done. Pending merge of pull request on branch #39
