### ISSUE TITLE
P1 Metadata (OCR): Improve Metadata Quality

### ISSUE THREAD

**Issue by higorspinto** [CivicActions/ckanext-edscrapers#58]
Description: Improve metadata quality from P1 Office of Civil Rights parser

TASKS

- [x] Ensure datasets produced have a description metadata 

- [x] Ensure datasets have a publisher metadata

- [x] Improve other metadata (use defaults where available)

Acceptance criteria:

- [x] Metadata quality from the parser has been improved
- [x] Have values for the high priority metadata available or set default values (if available)

[Jira card](https://open-data-ed.atlassian.net/browse/OD-537?atlOrigin=eyJpIjoiMjRmMzFhMmE4MTEzNGU2NzgyOGQxYWE1YjkzNzMyNmIiLCJwIjoiaiJ9)

**Comment by osahon-okungbowa** [comment]
Est 1 day
