### ISSUE TITLE
P2 Metadata (OCTAE): Improve Metadata Quality

### ISSUE THREAD

**Issue by higorspinto** [CivicActions/ckanext-edscrapers#59]
Description: Improve metadata quality from P2 Office of Career, Technical and Adult Education parser

TASKS

- [x] Ensure datasets produced have a description metadata 

- [x] Ensure datasets have a publisher metadata

- [x] Improve other metadata (use defaults where available)

Acceptance criteria:

- [x] Metadata quality from the parser has been improved
- [x] Have values for the high priority metadata available or set default values (if available)

[Jira Card](https://open-data-ed.atlassian.net/browse/OD-538?atlOrigin=eyJpIjoiMjFmYmI0ZjMwOWZkNGMxMWE2MjY5NGI4YmE2YTQ4MzciLCJwIjoiaiJ9)

**Comment by osahon-okungbowa** [comment]
Est 1 day
