### ISSUE TITLE
P3 Metadata (OPE): Improve Metadata Quality

### ISSUE THREAD

**Issue by higorspinto** [CivicActions/ckanext-edscrapers#60]
Description: Improve metadata quality from P3 Office of Postsecondary Education parser

TASKS

- [x] Ensure datasets produced have a description metadata 

- [x] Ensure datasets have a publisher metadata

- [x] Improve other metadata (use defaults where available)

Acceptance criteria:

- [x] Metadata quality from the parser has been improved
- [x] Have values for the high priority metadata available or set default values (if available)

[Jira Card](https://open-data-ed.atlassian.net/browse/OD-539?atlOrigin=eyJpIjoiZDM5ZjllOTFkMTZmNDUwNDk1MmI0Y2JlOWRjYjA1NTYiLCJwIjoiaiJ9)

**Comment by osahon-okungbowa** [comment]
Est 1 day
