### ISSUE TITLE
P4 Metadata (OELA): Improve Metadata Quality

### ISSUE THREAD

**Issue by higorspinto** [CivicActions/ckanext-edscrapers#61]
Description: Improve metadata quality from P4 Office of English Language Acquisition parser
TASKS

- [x] Ensure datasets produced have a description metadata 

- [x] Ensure datasets have a publisher metadata

- [x] Improve other metadata (use defaults where available)

Acceptance criteria:

- [x] Metadata quality from the parser has been improved
- [x] Have values for the high priority metadata available or set default values (if available)

[Jira Card](https://open-data-ed.atlassian.net/browse/OD-540?atlOrigin=eyJpIjoiNTQzODgzYTY0ZGEwNDE5Y2I5MThhNDVjMTFkYTQ5MzYiLCJwIjoiaiJ9)

**Comment by osahon-okungbowa** [comment]
Est 1 day
