### ISSUE TITLE
P5 Metadata (OSERS): Improve Metadata Quality

### ISSUE THREAD

**Issue by higorspinto** [CivicActions/ckanext-edscrapers#62]
Description: Improve metadata quality from P5 Office of Special Education and Rehabilitative Services parser

TASKS

- [x] Ensure datasets produced have a description metadata 

- [x] Ensure datasets have a publisher metadata

- [x] Improve other metadata (use defaults where available)

Acceptance criteria:

- [x] Metadata quality from the parser has been improved
- [x] Have values for the high priority metadata available or set default values (if available)

[Jira Card](https://open-data-ed.atlassian.net/browse/OD-541?atlOrigin=eyJpIjoiYzM4ZWI1OGQzMDBhNGYyYWE1OTZmNGIyMTRiN2UyYmUiLCJwIjoiaiJ9)

**Comment by osahon-okungbowa** [comment]
Est 1 day
