### ISSUE TITLE
P8 Metadata (ed.gov): Improve Metadata Quality

### ISSUE THREAD

**Issue by higorspinto** [CivicActions/ckanext-edscrapers#65]
Description: Improve metadata quality from P8 ed.gov parser. (highest priority)

TASKS

- [x] Ensure datasets produced have a description metadata 

- [x] Create more parsers for the variant page structures

Acceptance criteria:

- [x] Metadata quality from the parser has been improved
- [x] Have values for all the metadata fields (default values at least)

[Jira Card](https://open-data-ed.atlassian.net/browse/OD-544?atlOrigin=eyJpIjoiMTZjMDRiODcyNzZjNDVkYjlmZWUyNTQ4ZTJjZmM0ZjgiLCJwIjoiaiJ9)

**Comment by osahon-okungbowa** [comment]
Est 2 - 3 (_possibly_ 1 more parser may be created)
