### ISSUE TITLE
P9 Metadata (NCES): Improve Metadata Quality

### ISSUE THREAD

**Issue by higorspinto** [CivicActions/ckanext-edscrapers#66]
Description: Improve metadata quality from P9 NCES parser. (highest priority)

TASKS

- [x] Ensure datasets produced have a description metadata 

- [x] Create more parsers for the variant page structures

Acceptance criteria:

- [x] Metadata quality from the parser has been improved
- [ ] Have values for all the metadata fields (default values at least)

[Jira Card](https://open-data-ed.atlassian.net/browse/OD-545?atlOrigin=eyJpIjoiYTdlZmYzNzJkYjM5NGNlY2JkMzFhMjNhYzgyMzdkZDEiLCJwIjoiaiJ9)

**Comment by osahon-okungbowa** [comment]
Est 2 - 3 days (more parsers need to be created)
